# Generated by Django 3.1 on 2020-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
