# Generated by Django 3.1 on 2020-08-30 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200828_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='days_running',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='poll',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 12, 55, 32, 849953, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
