# Generated by Django 3.1 on 2020-09-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200904_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
