# Generated by Django 3.1 on 2020-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200913_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='publish_time',
            field=models.DateTimeField(),
        ),
    ]
