# Generated by Django 3.1 on 2020-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
