# Generated by Django 3.1 on 2020-09-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200916_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
